services:
  dev:
    image: yonix06/dev:devcontainer-db
    privileged: true
    entrypoint:
     - sleep
     - infinity
    init: true
    volumes:
      - ./apps:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appdata/postgresql:/var/lib/postgresql:rwx
    ## ports:
    ##   - 8000:8000
    ##   - 9000:9000
    ##   - 7001:7001
    ##   - 5432:5432
    ##   - 6379:6379

  mail:
    container_name: mail
    image: axllent/mailpit
    restart: always
    volumes:
      - ./devdata/mailpit:/data:rw
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@store.medusa
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5052:80'
    volumes:
      - ./devdata/pgadmin/lib:/var/lib/pgadmin


