services:
  dev:
    # image: yonix06/dev:devcontainer-db
    build:
      context: .
      dockerfile: './.devcontainer/Dockerfile.dev'
    container_name: dev
    restart: always
    privileged: true
    entrypoint:
     - sleep
     - infinity
    init: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["GPU-322f733b-33b7-4016-e0a5-a3b70d59a35b"]
              options:
                - "capabilities=compute,video,utility,compat32"

    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
      - 7001:7001
  
  store-database:
    container_name: store-database
    privileged: true
    image: postgres:17
    restart: always
    runtime: nvidia
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./appdata/postgresql/lib:/var/lib/postgresql/data:rwx


  mail:
    container_name: mail
    image: axllent/mailpit
    restart: always
    volumes:
      - ./devdata/mailpit:/data:rw
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  pgadmin:
    container_name: pgadmin4
    privileged: true
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@store.medusa
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5052:80'
    volumes:
      - ./devdata/pgadmin/lib:/var/lib/pgadmin


