services:
  store-frontend:
    container_name: store-frontend
    #image: yonix06/dev:store-frontend
    build:
      context: ./apps/store-storefront
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - store-database
      - redis
    volumes:
      - ./appdata/medusa/frontend:/apps/store-storefront
    networks:
      store:
        ipv4_address: 172.16.238.100

  store-backend:
    container_name: store-backend
    #image: yonix06/dev:store-backend
    build:
      context: ./apps/store
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9000:9000'
      - '7001:7001'
    depends_on:
      - store-database
      - redis
    volumes:
      - ./appdata/medusa/backend:/apps/store
    networks:
      store:
        ipv4_address: 172.16.238.104

#  store-database:
#    container_name: store-database
#    image: postgres:17
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./appdata/postgresql:/var/lib/postgresql:rwx
#    networks:
#      store:
#        ipv4_address: 172.16.238.101

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6479:6379'
    # Add a password with --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./appdata/redis:/data
    networks:
      store:
        ipv4_address: 172.16.238.102

  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - '9090:9000'
      - '9091:9001'
    command: minio server /data --console-address ":9001"
    volumes:
      - ./appdata/minio:/data
    environment:
      MINIO_ROOT_USER: medusa
      MINIO_ROOT_PASSWORD: password
    networks:
      store:
        ipv4_address: 172.16.238.103

networks:
  store:
    external: false
    name: store
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
    labels:
      com.docker.compose.project: store



