# Arguments and Environment variables
ARG BASE_IMAGE="yonix06/dev"
ARG VARIANT="node23-yarn4"
FROM $BASE_IMAGE:$VARIANT
ENV YARN_VERSION=canary
USER root
RUN mkdir -p /workspace
WORKDIR /workspace
RUN corepack enable

# Add some sources
RUN apt-get install -y postgresql-common ca-certificates curl && /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

# RUN sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
# RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

# Install dev tools & deps
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update && apt-get -y install nano git wget mkcert bash zsh openssh-client software-properties-common \
    redis-server libpq5 postgresql-17 postgresql-client postgresql-client-common fonts-powerline \
    && apt-get autoremove -y

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/romkatv/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
RUN echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >> ~/.zshrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
RUN chsh -s /bin/zsh
RUN curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

# Enable Dev Services
RUN systemctl enable redis-server postgresql

# Install npm deps
RUN yarn init -w
RUN yarn add nx@latest @medusajs/medusa-cli eslint prettier typescript tslint tslint-to-eslint-config tsx ts-node dotenv

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# [5432]-postgresql [6379]-redis [8000]-medusajs-storefront [7001]-medusajs-backend-api [9000]-medusajs-backend+admin
EXPOSE 5432
EXPOSE 6379
EXPOSE 7001
EXPOSE 8000
EXPOSE 9000

VOLUME /workspace

CMD [ "zsh" ]
