# Arguments and Environment variables
ARG BASE_IMAGE="yonix06/dev"
ARG VARIANT="node23-yarn4"
FROM $BASE_IMAGE:$VARIANT
ENV YARN_VERSION=canary
USER root
RUN mkdir -p /workspace
WORKDIR /workspace
RUN corepack enable

# Add Packages
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update 
RUN apt-get -y install apt-utils bash \
    nano git wget mkcert bash zsh openssh-client \
    fonts-powerline \
    && apt-get autoremove -y

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/romkatv/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
RUN echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >> ~/.zshrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
RUN chsh -s /bin/zsh
RUN curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

# Install npm deps
RUN yarn init -w
RUN yarn add nx@latest @medusajs/medusa-cli eslint prettier typescript tslint tslint-to-eslint-config tsx ts-node dotenv

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#   [8000]-medusajs-storefront [7001]-medusajs-backend-api [9000]-medusajs-backend+admin
EXPOSE 7001
EXPOSE 8000
EXPOSE 9000

VOLUME /workspace

CMD [ "zsh" ]
