# Arguments and Environment variables
ARG BASE_IMAGE="yonix06/dev"
ARG VARIANT="node23-yarn4"
FROM $BASE_IMAGE:$VARIANT
ENV YARN_VERSION=canary
RUN mkdir -p /workspace
WORKDIR /workspace
RUN corepack enable

# Install dev tools & deps
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update && apt-get -y install postgresql-common git curl wget mkcert bash zsh ca-certificates openssh-client software-properties-common \
    redis webdis libpq5 postgresql postgresql-client postgresql-client-common fonts-powerline \
    && apt-get autoremove -y
USER node
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/romkatv/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
RUN echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >> ~/.zshrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
USER root
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/romkatv/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
RUN echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >> ~/.zshrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
RUN chsh -s /bin/zsh
RUN curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
# Enable Dev Services
RUN systemctl enable redis-server postgresql

# Install npm deps
RUN yarn dlx add nx medusajs eslint prettier typescript tslint tslint-to-eslint-config tsx ts-node dotenv

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# [5432]-postgresql [6379]-redis [8000]-medusajs-storefront [7001]-medusajs-backend-api [9000]-medusajs-backend+admin
EXPOSE 5432
EXPOSE 6379
EXPOSE 7001
EXPOSE 8000
EXPOSE 9000

VOLUME /home/node/app

CMD [ "zsh" ]
