name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build a better node with updated yarn
      run: docker build './.devcontainer/' -f 'Dockerfile.ubernode' -t yonix06/dev:node23-yarn4$(date +%s)
    - name: Build the devcontainer with tools
      run: docker build './.devcontainer/' -f 'Dockerfile.dev' -t yonix06/dev:devcontainer-db$(date +%s)

