name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -f './.devcontainer/Dockerfile.ubernode' -t yonix06/dev:node23-yarn4$(date +%s) && docker build . -f './.devcontainer/Dockerfile.dev' -t yonix06/dev:devcontainer-db$(date +%s)

